Public Class Lists : Inherits List(Of FileContainer) : End Class
Public Class VesselList : Inherits List(Of Vessel) : End Class
Public Class MixtureList : Inherits List(Of Mixture) : End Class
Public Class PersonList : Inherits List(Of Person) : End Class
Public Class SynonymList : Inherits List(Of Synonym) : End Class
Public Class ProducedMixtureList : Inherits List(Of ProducedMixture) : End Class
Public Class ProcessTestList : Inherits List(Of ProcessTest) : End Class
Public Class PreservativeList : Inherits List(Of Preservative) : End Class
Public Class IngredientList : Inherits List(Of Ingredient) : End Class